# Generated by Django 2.0.5 on 2018-07-18 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddAgents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'add_agents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('receive_email', models.IntegerField(default=1)),
                ('password', models.CharField(max_length=255)),
                ('admin', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('noti_noti', models.IntegerField(default=0)),
                ('noti_chat', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'agents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ForwardTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('receiverid', models.ForeignKey(db_column='receiverid', on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='user.Agents')),
                ('senderid', models.ForeignKey(db_column='senderid', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user.Agents')),
            ],
            options={
                'db_table': 'forward_tickets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TicketAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentid', models.ForeignKey(db_column='agentid', on_delete=django.db.models.deletion.CASCADE, to='user.Agents')),
            ],
            options={
                'db_table': 'ticket_agent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TicketLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('agentid', models.ForeignKey(db_column='agentid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenttl', to='user.Agents')),
            ],
            options={
                'db_table': 'ticket_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('chat', models.CharField(max_length=30, null=True)),
                ('content', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('datestart', models.DateTimeField()),
                ('dateend', models.DateTimeField()),
                ('attach', models.FileField(blank=True, null=True, upload_to='photos')),
                ('note', models.TextField()),
                ('lv_priority', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tickets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TopicAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentid', models.ForeignKey(db_column='agentid', on_delete=django.db.models.deletion.CASCADE, to='user.Agents')),
            ],
            options={
                'db_table': 'topic_agent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('leader', models.ForeignKey(db_column='agentid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Agents')),
            ],
            options={
                'db_table': 'topics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('receive_email', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('noti_noti', models.IntegerField(default=0)),
                ('noti_chat', models.IntegerField(default=0)),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='topicagent',
            name='topicid',
            field=models.ForeignKey(db_column='topicid', on_delete=django.db.models.deletion.CASCADE, to='user.Topics'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='sender',
            field=models.ForeignKey(db_column='sender', on_delete=django.db.models.deletion.CASCADE, to='user.Users'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='topicid',
            field=models.ForeignKey(db_column='topicid', on_delete=django.db.models.deletion.CASCADE, to='user.Topics'),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='ticketid',
            field=models.ForeignKey(db_column='ticketid', on_delete=django.db.models.deletion.CASCADE, related_name='tickettl', to='user.Tickets'),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='userid',
            field=models.ForeignKey(db_column='userid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertl', to='user.Users'),
        ),
        migrations.AddField(
            model_name='ticketagent',
            name='ticketid',
            field=models.ForeignKey(db_column='ticketid', on_delete=django.db.models.deletion.CASCADE, to='user.Tickets'),
        ),
        migrations.AddField(
            model_name='forwardtickets',
            name='ticketid',
            field=models.ForeignKey(db_column='ticketid', on_delete=django.db.models.deletion.CASCADE, to='user.Tickets'),
        ),
        migrations.AddField(
            model_name='addagents',
            name='receiverid',
            field=models.ForeignKey(db_column='receiverid', on_delete=django.db.models.deletion.CASCADE, related_name='receiveradd', to='user.Agents'),
        ),
        migrations.AddField(
            model_name='addagents',
            name='senderid',
            field=models.ForeignKey(db_column='senderid', on_delete=django.db.models.deletion.CASCADE, related_name='senderadd', to='user.Agents'),
        ),
        migrations.AddField(
            model_name='addagents',
            name='ticketid',
            field=models.ForeignKey(db_column='ticketid', on_delete=django.db.models.deletion.CASCADE, to='user.Tickets'),
        ),
    ]
