# Generated by Django 2.0.5 on 2018-07-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='expired',
            field=models.IntegerField(default=0),
        ),
    ]
