# Generated by Django 2.0.5 on 2018-07-26 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tickets_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.IntegerField()),
            ],
            options={
                'db_table': 'level_priority',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tickets',
            name='priority',
            field=models.ForeignKey(db_column='priority', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.LevelPriority'),
        ),
    ]
