# Generated by Django 2.1.1 on 2018-09-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('image_name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('flavor', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('created', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'serverVM',
                'managed': True,
            },
        ),
    ]
