# Generated by Django 2.1.1 on 2018-09-17 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_ops'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Server',
        ),
    ]
