# Generated by Django 2.1.1 on 2018-09-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_delete_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('ram', models.IntegerField()),
                ('vcpus', models.IntegerField()),
                ('disk', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('created', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'serverVM',
                'managed': True,
            },
        ),
    ]
