# Generated by Django 2.1.1 on 2018-09-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_server'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Server',
        ),
    ]
