# Generated by Django 2.1.1 on 2018-09-17 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_auto_20180917_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255, null=True)),
                ('ram', models.IntegerField()),
                ('vcpus', models.IntegerField()),
                ('disk', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('created', models.CharField(max_length=255, null=True)),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'serverVM',
                'managed': True,
            },
        ),
    ]
