# Generated by Django 2.1.1 on 2018-09-17 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('created', models.DateTimeField()),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(db_column='server', on_delete=django.db.models.deletion.CASCADE, to='superadmin.Server')),
            ],
            options={
                'db_table': 'oders',
                'managed': True,
            },
        ),
    ]
