# Generated by Django 2.1.2 on 2018-11-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_myuser_token_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='token_expired',
            field=models.DateTimeField(null=True),
        ),
    ]
