# Generated by Django 2.1.2 on 2018-11-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0014_auto_20181114_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='money',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
