# Generated by Django 2.1.2 on 2018-11-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0015_myuser_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='money',
            field=models.CharField(default='10000', max_length=100),
        ),
    ]
