# Generated by Django 2.1.2 on 2018-11-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0016_auto_20181116_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oders',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
