# Generated by Django 2.1.2 on 2018-11-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0017_auto_20181116_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='money',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
