# Generated by Django 2.0.5 on 2018-07-27 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupService',
            new_name='GroupServices',
        ),
        migrations.AddField(
            model_name='agents',
            name='groupserviceid',
            field=models.ForeignKey(db_column='groupserviceid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.GroupServices'),
        ),
        migrations.AddField(
            model_name='services',
            name='groupserviceid',
            field=models.ForeignKey(db_column='groupserviceid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.GroupServices'),
        ),
    ]
