# Generated by Django 2.0.5 on 2018-07-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180727_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='service',
            new_name='serviceid',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='title',
            new_name='thong_so_kt',
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
