# Generated by Django 2.0.5 on 2018-07-31 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tickets_date_clode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='date_clode',
            new_name='date_close',
        ),
    ]
