# Generated by Django 2.0.5 on 2018-07-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180731_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='date_close',
            field=models.DateField(null=True),
        ),
    ]
