# Generated by Django 2.0.5 on 2018-07-31 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='leader_bk',
            field=models.ForeignKey(db_column='agentid_bk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_bk', to='user.Agents'),
        ),
        migrations.AlterField(
            model_name='services',
            name='leader',
            field=models.ForeignKey(db_column='agentid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to='user.Agents'),
        ),
    ]
