# Generated by Django 2.0.5 on 2018-07-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180731_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='date_clode',
            field=models.DateTimeField(null=True),
        ),
    ]
