# Generated by Django 2.0.5 on 2018-08-20 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180731_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('date', models.DateTimeField()),
                ('agentid', models.ForeignKey(db_column='agentid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentcl', to='user.Agents')),
                ('ticketid', models.ForeignKey(db_column='ticketid', on_delete=django.db.models.deletion.CASCADE, related_name='ticketcl', to='user.Tickets')),
            ],
            options={
                'db_table': 'comments_log',
                'managed': True,
            },
        ),
    ]
